name: subtypes-core
version: 0.1.0
synopsis: Lift subtypes into types
category: Generics
license: BSD3
license-file: LICENSE
author: Patrick Bahr, Tom Hvitved, Yair Chuchem
dependencies: 
  - base >= 4.16 && < 4.20
library:
  source-dirs: src
  ghc-options: -W
tests:
  test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - subtypes-core
